### ISSUE TITLE
While adding New org peer all other existing peer pods get lost.

### ISSUE THREAD

**Issue by abhisamant7** [hyfen-nl/PIVT#100]
Hi All,

When Adding new org to my exiting scale-raft-tls network I lost my old orgs peers and orderer pods. I followed [this](https://github.com/hyfen-nl/PIVT#adding-new-peer-organizations). and when I used `helm upgrade hlf-kube ./hlf-kube -f samples/simple/network.yaml -f samples/simple/crypto-config.yaml
` my all old peers and orderer pods get terminated and not up automatically. 

Please help me I didn't understand why this happened as I missed something?

**Comment by raftAtGit** [comment]
well, if you make `helm upgrade` with `samples/simple/`, it's natural that `samples/scaled-raft-tls` peer/orderer pods will be terminated ;)

**Comment by abhisamant7** [comment]
Sorry for mistype command here as I used command for sample/scaled-raft-tls only. It was different issue which I found I fixed it 
so I closing this issue
