### ISSUE TITLE
I am unable to add repo kubernetes-charts-incubator - 403 error

### ISSUE THREAD

**Issue by rhousand** [hyfen-nl/PIVT#101]
Has this repo moved or is there a newer project? I am getting the following error when trying to install the incubator repo:

helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
Error: looks like "http://storage.googleapis.com/kubernetes-charts-incubator" is not a valid chart repository or cannot be reached: failed to fetch http://storage.googleapis.com/kubernetes-charts-incubator/index.yaml : 403 Forbidden

Thanks!

Ryan

**Comment by armandjanssen1978** [comment]
Hello Ryan,

They have changed the location to https://charts.helm.sh/incubator 

See https://helm.sh/blog/new-location-stable-incubator-charts/ for more info.

**Comment by raftAtGit** [comment]
thanks for the notification guys. updated the readme and also `hlf-kube/requirements.yaml` for the new incubator location

**Comment by rhousand** [comment]
Thanks for the quick response. All good now!
