### ISSUE TITLE
how to deal with  the problem of pod ClusterIPs are not stable 

### ISSUE THREAD

**Issue by nanadeis** [hyfen-nl/PIVT#102]
as README.md mentioned, pod ClusterIPs are not stable。So when ClusterIP changes， we need to update the hostAlias。But how do we know when to update？And POD need to restart  when update，frequent updates maybe impair service performance？And it doesn't take advantage of the service！
Maybe we can modify the source code for cryptogen， let TLS certificates  match service names， is it a good idea？
Or is there any way to map the domain name to the service name？
Does anyone have any good advice for dealing with this problem？thanks a lot！

**Comment by LudoNieuw** [comment]
Hi there, as stated in the readme, the host aliases gather the service  ips
which are stable. You can, using tls, delete the peer and ordered pods as
many times you want, without issues as the connection is made via the
services.

Hope that answers your question. If not, you can always try it out to see
that it just works :)

Best!

Ludo
Op vr 22 jan. 2021 om 03:43 schreef nanadeis <notifications@github.com>

**Comment by nanadeis** [comment]
@LudoNieuw thank you very much！ I misread it, I mistakenly thought that Hostalias used ClusterIP 😢
