### ISSUE TITLE
Question: How to create another channel with new organization and existing one organization in Scaled-raft-tls 

### ISSUE THREAD

**Issue by abhisamant7** [hyfen-nl/PIVT#103]
Hi,

I have one requirement where I want to create another channel  on existing running network in  Scaled-raft-tls with    one new organization and existing one organization, So I am confused how to implement it I have to create new network.yaml file or I can ad d details of new org in same network.yaml file. If possible someone give some hint on this?

Thanks in Advance

**Comment by raftAtGit** [comment]
1. Update your `configtx.yaml`, `crypto-config.yaml` and `network.yaml` (no need for a new one)
2. Follow the steps in the readme: _Adding new peer organizations/Raft orderer network_ 
a. `extend.sh` -> create new crypto material
b. helm upgrade + collect host aliases + helm upgrade 
c. run `peer-org-flow` -> create the new organization, add to consortiums as defined in `configtx.yaml`
d. run `channel-flow` -> create the new channel

as mentioned in the readme, persistence should be enabled. o/w peer/orderer pods will loose all data during restart

**Comment by abhisamant7** [comment]
Thanks for reply. I will try same way as you mention. 
One thing to add here in my query when If want to change the channel name except "common" channel name which file I need to change the channel name?

**Comment by raftAtGit** [comment]
you cannot change the channel name. at least you cannot do it with our declarative workflows. not sure if even possible with Fabric tools.

if you change the channel name in `network.yaml`, it will be considered as a new channel and will be created by `channel-flow`. the old one will remain

**Comment by abhisamant7** [comment]
Thanks for that also

**Comment by abhisamant7** [comment]
Hi @raftAtGit ,

I am getting error while  doing below step. I have changed the config.tx, crypto-config.yaml and network.yaml files, however getting error which I attached to screenshot
![Screenshot from 2021-01-29 16-49-56](https://user-images.githubusercontent.com/21276072/106270286-beeddf80-6253-11eb-8d29-f248bf6c889d.png)


> 2\. c. run `peer-org-flow` -> create the new organization, add to consortiums as defined in `configtx.yaml`

**Comment by raftAtGit** [comment]
> controller is not configured with a default archive location

-> you didnt configure Argo to use artifacts. check argo docs for how to do it. 

and please make sure you can run an Argo sample with artifacts before proceeding:
https://argoproj.github.io/argo/examples/#artifacts

**Comment by abhisamant7** [comment]
So here I have query that for adding new org with new channel I need  configure Argo everytime?

**Comment by raftAtGit** [comment]
not every time, you need to do it once

**Comment by abhisamant7** [comment]
so here let me explain 
firstly I already have blockchain setup with 2 orgs which was running fine  on scaled-raft-tls sample. Now I want to add new org which which will join new channel with one of org in previous two orgs. So I follow [this](https://github.com/hyfen-nl/PIVT/tree/f754228503afcd7f93e45b719663414eaf77cf10#adding-new-peer-organizations) link and Update my configtx.yaml, crypto-config.yaml and network.yaml files with adding new org and channel, however when I run command ` helm template peer-org-flow/ -f samples/scaled-raft-tls/configtx.yaml -f samples/scaled-raft-tls/crypto-config.yaml -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/hostAliases.yaml | argo submit - --watch` I am getting error which I mentioned in screenshot. 
So here my query I need to configure Argo to use artifacts?
Please suggest me

**Comment by raftAtGit** [comment]
yes, to use any flow which depends on Argo artifacts (backup/restore and new-peer-org flows) you need to configure Argo to use some artifactory. easiest is to install and use Minio

**Comment by abhisamant7** [comment]
So to add new org and channel which argo file I need to configure in this project?

**Comment by raftAtGit** [comment]
check Argo docs please

**Comment by abhisamant7** [comment]
thanks
