### ISSUE TITLE
Getting error  launch our Raft based Fabric network as Error: found in requirements.yaml, but missing in charts/ directory: kafka

### ISSUE THREAD

**Issue by abhisamant7** [hyfen-nl/PIVT#104]
I am getting error while launch our Raft based Fabric network as  Error: found in requirements.yaml, but missing in charts/ directory: kafka. 

I have installed  chart dependencies as 
```
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
helm dependency update ./hlf-kube/
```
however when execute command getting error as
```
  Downloading kafka from repo http://storage.googleapis.com/kubernetes-charts-incubator
Save error occurred:  could not find : chart kafka not found in http://storage.googleapis.com/kubernetes-charts-incubator
```
and when I  am launching  Raft based Fabric network  using command  ` helm install ./hlf-kube --name hlf-kube -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml`  getting error as` Error: found in requirements.yaml, but missing in charts/ directory: kafka`  

please suggest me how to resolve it?

Thanks

**Comment by LudoNieuw** [comment]
Hi there, 

The repo moved, master branch was updated to fix this: https://github.com/hyfen-nl/PIVT/commit/f754228503afcd7f93e45b719663414eaf77cf10#diff-1b1014578b503056dc88218ef852fcaed3097575c65248b98281b58a33e1c389

If you pull master again, your issue is fixed.

Best,

Ludo

**Comment by abhisamant7** [comment]
Thanks

**Comment by abhisamant7** [comment]
Thanks
