### ISSUE TITLE
How can i migrate my Fabric Network 1.4.3 to 2.0  or latest version?

### ISSUE THREAD

**Issue by aswath-edx** [hyfen-nl/PIVT#111]

**Comment by raftAtGit** [comment]
well, you basically increase the [Fabric version](https://github.com/hyfen-nl/PIVT/blob/master/fabric-kube/hlf-kube/values.yaml#L5) in the values file and then make a Helm update.

unless they didn't break backwards compatibility, this will make newer binaries work with existing channel/application/orderer capabilities.

then you can use the [channel-update-flow](https://github.com/hyfen-nl/PIVT#updating-channel-configuration) to update the channel/application/orderer capabilities. 

but beware, with application capabilities v2_0+ you can not use the chaincode flow of this repo. new chaincode lifecycle is not yet supported with our chaincode flow. but you can of course use other means to package and deploy your chaincodes.

using new binaries but not updating application capabilities is also an option to continue using our chaincode flow. 

the existing chaincodes will [continue to work](https://hyperledger-fabric.readthedocs.io/en/latest/upgrade_to_newest_version.html#chaincode-lifecycle) regardless of this update.

if you need to update orderer (system) channels, you need to manually do that. 

**important:** Pay extreme attention when setting capability versions. If you set them to a non-existing value, like V1_4_3, orderers will accept the value but peers will crash immediately when they receive the update. To my knowledge, there is no way of [reverting it back](https://lists.hyperledger.org/g/fabric/message/7775) except restoring from a backup.

**Comment by aswath-edx** [comment]
but in fabric 2.3 version the chaincode run as external right? so  when we upgrade to 2.3 how to old chaincode run as external. how it work 2.3 version?

**Comment by aswath-edx** [comment]
> well, you basically increase the [Fabric version](https://github.com/hyfen-nl/PIVT/blob/master/fabric-kube/hlf-kube/values.yaml#L5) in the values file and then make a Helm update.
> 
> unless they didn't break backwards compatibility, this will make newer binaries work with existing channel/application/orderer capabilities.
> 
> then you can use the [channel-update-flow](https://github.com/hyfen-nl/PIVT#updating-channel-configuration) to update the channel/application/orderer capabilities.
> 
> but beware, with application capabilities v2_0+ you can not use the chaincode flow of this repo. new chaincode lifecycle is not yet supported with our chaincode flow. but you can of course use other means to package and deploy your chaincodes.
> 
> using new binaries but not updating application capabilities is also an option to continue using our chaincode flow.
> 
> the existing chaincodes will [continue to work](https://hyperledger-fabric.readthedocs.io/en/latest/upgrade_to_newest_version.html#chaincode-lifecycle) regardless of this update.
> 
> if you need to update orderer (system) channels, you need to manually do that.
> 
> **important:** Pay extreme attention when setting capability versions. If you set them to a non-existing value, like V1_4_3, orderers will accept the value but peers will crash immediately when they receive the update. To my knowledge, there is no way of [reverting it back](https://lists.hyperledger.org/g/fabric/message/7775) except restoring from a backup.

**Comment by raftAtGit** [comment]
To my knowledge, Fabric 2.0+ can run chaincodes as external services but it doesn't have to

**Comment by aswath-edx** [comment]
in 1,4 kube network chain code run as inside peer pod right ?. so how it possible after upgrade fabric version to run old chiancode in new fabric version

**Comment by raftAtGit** [comment]
inside the peer pod or next to it (in the same host). depends on the [peer dind](https://github.com/hyfen-nl/PIVT/blob/master/fabric-kube/hlf-kube/values.yaml#L56) value.

To my knowledge, Fabric 2.0+ gives the option of running chaincodes as external services, but this is not mandatory and you can still run the chaincodes internally.
