### ISSUE TITLE
CREATE channel workflows is in pending state and does not move

### ISSUE THREAD

**Issue by Marek00Malik** [hyfen-nl/PIVT#93]
Hi, 
I could not find any issue that was addressing this problem. 
When following the instructions to create and join a channel the Argo workflows seem to be stuck in a Pending state. 

The command I'm running is: 
```
helm template channel-flow/ -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml -f samples/scaled-raft-tls/hostAliases.yaml | argo submit - --watch
```

Could anyone help? I don't see any logs so I don't know where to start even. 
My setup is: 
kubernetes: 
```
➜  fabric-kube git:(master) ✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
argo:
```
✗ argo version
argo: v2.11.4
  BuildDate: 2020-10-14T22:04:23Z
  GitCommit: 571bff1fe4ad7e6610ad04d9a048091b1e453c5a
  GitTreeState: clean
  GitTag: v2.11.4
  GoVersion: go1.13.15
  Compiler: gc
```

I'm running it on HL Fabric 2.2.1 binaries, but I would imagine that there would be some error/logging if there are versioning issues. 

Anyone could help this ?

**Comment by raftAtGit** [comment]
this indicates an issue with your Argo setup. checking Argo `workflow-controller` pod's logs might help.

make sure you can run any Argo sample workflow before continuing.

**Comment by Marek00Malik** [comment]
wow, it worked like a charm. 
I had Argo workflow-controller installed, maybe it got deleted when I did 
```
argo delete --all
helm delete hlf-kube --purge
```

Again, thank you for such a quick replay. 
Cheers and stay safe!

**Comment by raftAtGit** [comment]
yes, it works like a charm ;)
