### ISSUE TITLE
Passing java binaries to be installed as chain codes

### ISSUE THREAD

**Issue by Marek00Malik** [hyfen-nl/PIVT#94]
At first, I would like to thank you guys for doing a great job. 
The tool is done and documented very well, all the samples are extremely useful. 

I'm currently trying to adapt your tool to use with the new chain codes with lifecycles, to be exact java-based chain codes. 
I'm trying to install them on all peers, the problem I have is that I'm not able to move the binaries to the cluster with the current state, as the helm file is much too long. 
The chaincodes after preparation for deploying are around 2-5 MB so not that big, but the file is too long to be copied into k8s using ConfigMap service. Do you have any idea how to copy files that are larger so they can be accessed in helm charts?

**Comment by raftAtGit** [comment]
thanks for the nice words :)

first I need to say I'm not much familiar with Fabric 2 chaincode lifecycle.

two things comes to my mind:

1. why are you trying to pass chaincode with its dependencies to the Helm chart? instead pass only the source code as it's now, and install the dependencies inside chaincode flow.
2. o/w you can think of putting chaincode with dependencies to a location where chaincode flow can download

**Comment by Marek00Malik** [comment]
I did as you mentioned, I have put the installation package in S3 and made the worklfow download it on each installation.
